language: go
go:
    - 1.11.x
env:
  - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  - goveralls -service=travis-ci
